apiVersion: v1
kind: Template
metadata:
  name: insights-chrome
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: Frontend
    metadata:
      name: chrome
    spec:
      envName: ${ENV_NAME}
      deploymentRepo: https://github.com/RedHatInsights/insights-chrome
      title: Chrome
      image: ${IMAGE}:${IMAGE_TAG}
      API:
        versions:
          - v1
      module:
        manifestLocation: "/apps/chrome/js/fed-mods.json"
        config:
          ssoUrl: ${SSO_URL}
      frontend:
        paths:
          - /
          - /config/chrome
parameters:
  - name: ENV_NAME
    required: true
  - name: IMAGE_TAG
    required: true
  - name: SSO_URL
    required: true
  - name: IMAGE
    value: quay.io/cloudservices/insights-chrome-frontend
