export const testData = [
  {
    id: 1,
    title: 'TEST NOTIFICATION',
    description: 'This is a notification test bro, bet, no cap, on god.',
    read: false,
    source: 'ur mom lolz',
    created: new Date().toString(),
  },
  {
    id: 2,
    title: 'PRUEBA DE NOTIFICACIONES',
    description: 'This is a notification test bro, bet, no cap, on god.',
    read: false,
    source: 'RHEL',
    created: new Date().toString(),
  },
  {
    id: 3,
    title: 'NOTIFICATION TEST',
    description: 'This is a notification test bro, bet, no cap, on god.',
    read: false,
    source: 'RBAC',
    created: new Date().toString(),
  },
  {
    id: 4,
    title: 'ALERT',
    description: 'This is a notification test bro, bet, no cap, on god.',
    read: false,
    source: 'REMEDIATIONS',
    created: new Date().toString(),
  },
  {
    id: 5,
    title: 'HONEY I BLEW UP THE BACKEND AGAIN',
    description: 'This is a notification test bro, bet, no cap, on god.',
    read: false,
    source: 'OpenShift',
    created: new Date().toString(),
  },
]
