apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/RedHatInsights/insights-chrome?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: '3'
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "master"
  creationTimestamp:
  labels:
    appstudio.openshift.io/application: chrome-frontend
    appstudio.openshift.io/component: insights-chrome
    pipelines.appstudio.openshift.io/type: build
  name: insights-chrome-on-push
  namespace: hcc-platex-services-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/hcc-platex-services-tenant/insights-chrome:{{revision}}
  - name: dockerfile
    value: ./Dockerfile
  pipelineRef:
    params:
      - name: url
        value: https://github.com/RedHatInsights/konflux-pipelines
      - name: revision
        value: main
      - name: pathInRepo
        value: pipelines/docker-build.yaml
    resolver: git
  taskRunTemplate:
    serviceAccountName: build-pipeline-insights-chrome
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      status: {}
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
