apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: e2e-tests
spec:
  params:
    - name: repo_url
      description: Git repository URL
      type: string
      default: '{{repo_url}}'
    - name: revision
      description: Git revision (branch, tag, sha)
      type: string
      default: '{{revision}}'
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        metadata:
          creationTimestamp:
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
  tasks:
    - name: clone-repository
      taskRef:
        name: git-clone-oci-ta
        bundle: quay.io/konflux-ci/tekton-catalog/task-git-clone-oci-ta:0.1@sha256:d35e5d501cb5f5f88369511f76249857cb5ac30250e1dcf086939321964ff6b9
      params:
        - name: url
          value: $(params.repo_url)
        - name: revision
          value: $(params.revision)
      workspaces:
        - name: output
          workspace: source
    - name: run-cypress-e2e
      runAfter:
        - clone-repository
      taskSpec:
        workspaces:
          - name: source
        steps:
          - name: run-cypress-e2e
            image: quay.io/redhat-user-workloads/rh-platform-experien-tenant/cypress-e2e-image/cypress-e2e-image:af9f17cb332f8e4a7f2e629bccbeeb1451490566
            workingDir: /workspace/source
            env:
              - name: E2E_URL
                valueFrom:
                  secretKeyRef:
                    name: e2e-frontend-tests-secrets
                    key: E2E_URL
              - name: E2E_USER
                valueFrom:
                  secretKeyRef:
                    name: e2e-frontend-tests-secrets
                    key: E2E_USER
              - name: E2E_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: e2e-frontend-tests-secrets
                    key: E2E_PASSWORD
            script: |
              #!/bin/bash
              set -ex
              npm i
              E2E_BASE=$E2E_URL E2E_USER=$E2E_USER E2E_PASSWORD=$E2E_PASSWORD npm run test:e2e
